#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Aggregate generated showcase reports into project-book material."""

from __future__ import annotations

import argparse
from pathlib import Path


SECTIONS = [
    ("1. Multimodal Evidence Cards And Consistency Checks", "safe/reports/multimodal_evidence_check_report.md"),
    ("2. Red-Team Attacks And Defense Loop", "safe/reports/redteam_showcase_report.md"),
    ("3. M-EPI Multimodal Evidence Pollution Inspection", "safe/reports/mepi_showcase_report.md"),
    ("4. Audit Chain And Tamper Detection", "safe/reports/audit_chain_report.md"),
]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="safe/reports/TECHNICAL_MATERIALS_FOR_PROJECT_BOOK.md")
    args = parser.parse_args()
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Technical Materials For SafePLC Project Book",
        "",
        "This file aggregates reusable report text generated by the SafePLC trusted RAG showcase scripts.",
        "",
    ]
    for title, report_path in SECTIONS:
        lines.append(f"## {title}")
        lines.append("")
        path = Path(report_path)
        if path.exists():
            lines.append(path.read_text(encoding="utf-8"))
        else:
            lines.append("Pending generation.")
        lines.append("")
    lines.extend(
        [
            "## 5. Technical Solution Summary",
            "",
            "SafePLC builds a reusable evidence chain for industrial trusted RAG. Multimodal evidence cards "
            "normalize text, tables, OCR, and pages; consistency checks detect cross-modal conflicts; M-EPI "
            "scores evidence pollution; red-team showcases compare baseline failure with protected behavior; "
            "and audit-chain reports demonstrate tamper-evident decision logging.",
            "",
        ]
    )
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
